using System.Reflection;
using System.Text.RegularExpressions;
using Clyr.Contracts;
using Clyr.Core;
using Clyr.Core.Execution;

namespace Clyr.ElevatedHelper;

/// <summary>
/// One-shot elevated helper. It accepts exactly one bootstrap argument — a pipe name generated by the requesting
/// CLYR process — connects to it, reads exactly one bounded request, independently revalidates and executes it,
/// writes exactly one bounded response, and exits. It never stays resident, never accepts a second request, never
/// launches another process, and never reads any command, script, or path from anywhere but the IPC request's
/// already-typed, non-polymorphic fields.
/// </summary>
internal static class Program
{
    private static readonly Regex PipeNamePattern = new("^Clyr\\.Helper\\.[0-9A-F]{32}$", RegexOptions.Compiled);

    private static async Task<int> Main(string[] args)
    {
        if (args.Length != 1 || !PipeNamePattern.IsMatch(args[0]))
        {
            Console.Error.WriteLine("clyr-helper: exactly one bootstrap pipe-name argument is required.");
            return 2;
        }
        if (!OperatingSystem.IsWindows())
        {
            Console.Error.WriteLine("clyr-helper: this helper only runs on Windows.");
            return 3;
        }

        var pipeName = args[0];
        var helperVersion = Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "0.0.0";
        var clock = new SystemClock();
        using var cts = new CancellationTokenSource();
        Console.CancelKeyPress += (_, eventArgs) => { eventArgs.Cancel = true; cts.Cancel(); };

        try
        {
            await ElevatedHelperIpc.RunOneShotAsync(pipeName, HelperProtocol.RequestTimeout,
                (request, cancellationToken) => Task.FromResult(ElevatedHelperRequestHandler.Handle(request, clock, helperVersion, cancellationToken)),
                cts.Token).ConfigureAwait(false);
            return 0;
        }
        catch (OperationCanceledException)
        {
            Console.Error.WriteLine("clyr-helper: timed out or was cancelled before a response was sent.");
            return 4;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or System.Text.Json.JsonException)
        {
            Console.Error.WriteLine("clyr-helper: the IPC channel or request was invalid.");
            return 5;
        }
    }
}
